# Generated by Django 3.1.6 on 2021-02-22 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comentariu', 'verbose_name_plural': 'Comentarii'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produs', 'verbose_name_plural': 'Produse'},
        ),
    ]
